### ISSUE TITLE
Add Status fields management

### ISSUE THREAD

**Issue by horis233** [IBM/ibm-secretshare-operator#5]
/kind feature

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]

Status management: 

We need to manage the status field to report the progress of secrets and configmaps copying.
The status could have two fields members and phase

```
status:
  members:
  - secret1: Completed
  - secret2: NotFound
  - configmap1: Updating
 Phase: Completed  
 ```

 

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]
